name: WhatsApp Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *' # Executa todos os dias às 12:00

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositório
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Instalar dependências
        run: |
          npm install

      - name: Rodar o bot
        run: |
          npm start
